The following table contains all of the `TenantResolver` implementations that ship with GORM and are usable out of the box. The package name has been shorted from `org.grails.datastore.mapping` to `o.g.d.m` for brevity:

[format="csv", options="header"]
|===
name,description
`o.g.d.m.multitenancy.resolvers.FixedTenantResolver`, Resolves against a fixed tenant id
`o.g.d.m.multitenancy.resolvers.SystemPropertyTenantResolver`, Resolves the tenant id from a system property called `gorm.tenantId`
`o.g.d.m.multitenancy.web.SubDomainTenantResolver`, Resolves the tenant id from the subdomain via DNS
`o.g.d.m.multitenancy.web.CookieTenantResolver`, Resolves the current tenant from an HTTP cookie named `gorm.tenantId` by default
`o.g.d.m.multitenancy.web.SessionTenantResolver`, Resolves the current tenant from the HTTP session using the attribute `gorm.tenantId` by default
|===

However, you have the flexibility to create your a custom tenant resolver is easy. In order to do that, create a class which implements
`org.grails.datastore.mapping.multitenancy.TenantResolver`. Given a request such as:

[source, bash, options=wrap]
----
## Request Duplicate
curl "http://localhost:8080/plan" \
     -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9....." \
     -H "Accept: application/json"
----

which contains a JWT token in the `Authorization` header.

Create a Custom Tenant Resolver which extracts the JWT token, re-hydrates it and
extracts the username.

[source,groovy]
.src/main/groovy/demo/CurrentUserByJwtTenantResolver.groovy
----
include::{sourceDir}/src/main/groovy/demo/CurrentUserByJwtTenantResolver.groovy[]
----

Define the Custom Tenant Resolver as a bean:

[source,groovy]
.grails-app/conf/spring/resources.groovy
----
include::{sourceDir}/grails-app/conf/spring/resources.groovy[tag=tenantResolverImport]
include::{sourceDir}/grails-app/conf/spring/resources.groovy[tag=beans]
include::{sourceDir}/grails-app/conf/spring/resources.groovy[tag=tenantResolverBean]
}
----

Create an Integration Test to test the custom Tenant Resolver.

[source,groovy]
.src/integration-test/groovy/demo/CurrentUserByJwtTenantResolverSpec.groovy
----
include::{sourceDir}/src/integration-test/groovy/demo/CurrentUserByJwtTenantResolverSpec.groovy[]
----