http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/[Grails Spring Security REST plugin] allows you to authenticate your application with a JWT token present in the `Authorization` header.  

Example: A request to `/plan` contains a JWT token in the `Authorization` header.

[source, bash, options=wrap]
----
## Request Duplicate
curl "http://localhost:8080/plan" \
     -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9....." \
     -H "Accept: application/json"
----

We can create Custom Tenant Resolver which extracts the JWT token, re-hydrates it and extracts the username.

[source,groovy]
.src/main/groovy/demo/CurrentUserByJwtTenantResolver.groovy
----
include::{sourceDir}/src/main/groovy/demo/CurrentUserByJwtTenantResolver.groovy[]
----

Define the Custom Tenant Resolver as a bean:

[source,groovy]
.grails-app/conf/spring/resources.groovy
----
include::{sourceDir}/grails-app/conf/spring/resources.groovy[tag=tenantResolverImport]
include::{sourceDir}/grails-app/conf/spring/resources.groovy[tag=beans]
include::{sourceDir}/grails-app/conf/spring/resources.groovy[tag=tenantResolverBean]
}
----

Create an Integration Test to test the custom Tenant Resolver.

[source,groovy]
.src/integration-test/groovy/demo/CurrentUserByJwtTenantResolverSpec.groovy
----
include::{sourceDir}/src/integration-test/groovy/demo/CurrentUserByJwtTenantResolverSpec.groovy[]
----

Next were are going to configure our app to use this custom tenant resolver. 

Configure Multi-Tenancy by modifying `application.yml`.

[source,yml]
.grails-app/conf/application.yml
----
grails
include::{sourceDir}/grails-app/conf/application.yml[tag=multiTenancyConfiguration]
----

<1> Define Multi-Tenancy mode as `DISCRIMINATOR`
<2> Set the Tenant Resolver class with a custom class which you will write later in this guide.